### ISSUE TITLE
Docker Zero Downtime deployments

### ISSUE THREAD

**Issue by jayfk** [cookiecutter/cookiecutter-django#1133]
This will complicate things a little, but is a nice to have.

Thoughts?

**Comment by pydanny** [comment]
Do it!

**Comment by webyneter** [comment]
@jayfk, how is this going? Can I be of any help?

**Comment by panuta** [comment]
I'd love to see this too.

**Comment by jayfk** [comment]
Djangopackages has it: 
https://github.com/djangopackages/djangopackages/blob/master/docker-compose.yml#L9-L35
https://github.com/djangopackages/djangopackages/blob/master/fabfile.py
https://github.com/djangopackages/djangopackages/blob/master/compose/caddy/Caddyfile#L6-L15

The main idea is to have two running Django containers that are load balanced by the webserver. 

- Code pushed
- First container is being rebuild and goes down
- Load balancer chooses second container to serve requests
- First container starts up
- Load balancer spreads requests evenly between new and old code
- Second container is being rebuild and goes down
- Load balancer picks the first container, is now serving only new code
- Second container starts up
- Load balancer picks up both containers and is now serving both old and new code

If someone wants to work on this, I'd be happy to review it.

**Comment by panuta** [comment]
Wondering what should we do if there's a new db migration in code pushed?

**Comment by jayfk** [comment]
You create a database migration first thats both compatible with the new and the old code and deploy it. Once that‘s complete, you deploy code changes to use the migrated scheme and finally you add a second migration that removes the old one.

**Comment by Andrew-Chen-Wang** [comment]
@browniebroke @jayfk @pydanny I'm not too acquainted with Traefik, but since we've moved on from caddy, here's something that could be useful if we keep trying Blue/Green deployment: https://www.katacoda.com/courses/distributed-microservices/3-blue-green-routing

Blue/Green deployment would work for non-async views (so no Channels or Django 3 web sockets, unless I read that README.md wrong) unless that load balancing configuration works by slowly moving traffic instead of immediate. Then again, I have no idea how it works and was wondering if this PR could be continued in development by someone who did know? Or should I create a new issue to track this so other GH users can see it more visibly?

**Comment by agusmakmun** [comment]
@jayfk I'm exploring this issue, and I found this package https://github.com/signalfx/maestro-ng
seems this package support for Orchestration of Docker-based & multi-host environments.

But, I didn't know how to implement it, probably somebody here want to test & create a example project which implementing this?

**Comment by foarsitter** [comment]
@agusmakmun In my opinion this project should deliver an container and stop there. How you deploy this container is up to you. 

I have some great experiences with `docker swarm` for zero downtime deployments. This article explains how to achieve this: https://betterprogramming.pub/zero-downtime-deployment-with-docker-swarm-d84d8d9d9a14 

The healthcheck that I'm using for a Django container is this one: 
```
/bin/bash -c "timeout 1 bash -c '</dev/tcp/localhost/5000' 2>/dev/null"
```

But beware for zero blue/green deployments, your migrations have to be backwards compatible. Otherwise your green version crashes after the migrations of blue : https://medium.com/3yourmind/keeping-django-database-migrations-backward-compatible-727820260dbb

**Comment by browniebroke** [comment]
> Djangopackages has it:
> [djangopackages/djangopackages@`master`/docker-compose.yml#L9-L35](https://github.com/djangopackages/djangopackages/blob/master/docker-compose.yml?rgh-link-date=2018-03-20T11%3A22%3A10Z#L9-L35)
> [djangopackages/djangopackages@`master`/fabfile.py](https://github.com/djangopackages/djangopackages/blob/master/fabfile.py?rgh-link-date=2018-03-20T11%3A22%3A10Z)
> [djangopackages/djangopackages@`master`/compose/caddy/Caddyfile#L6-L15](https://github.com/djangopackages/djangopackages/blob/master/compose/caddy/Caddyfile?rgh-link-date=2018-03-20T11%3A22%3A10Z#L6-L15)

Side note, the 1st link is out of date, because the compose file has been renamed. Here is the new link https://github.com/djangopackages/djangopackages/blob/03319cb4d7d9b4277cf8a8000d906b93996bc229/docker-compose.prod.yml#L8-L46

> In my opinion this project should deliver an container and stop there. How you deploy this container is up to you.

100% agree, this feels out of scope. Closing.
