### ISSUE TITLE
docker-compose -f local.yml stop|down causes some containers to exit with code 137

### ISSUE THREAD

**Issue by rmeno** [cookiecutter/cookiecutter-django#1743]
## What happened?
Docker containers correctly initialized and running locally but a shutdown call exits with the attached log message.

Seems like the datastores (postgres, redis) respond to the SIGTERM but docker has to issue a SIGKILL to their dependents.

## What should've happened instead?
All containers exiting on SIGTERM with a non-error status code

## Steps to reproduce
Install new cookiecutter project following steps listed in docs, section - Getting Up and Running Locally With Docker .

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Project generation options)
* Logs

```
cc_django_celerybeat_1 exited with code 137
cc_django_celeryworker_1 exited with code 137
redis_1         | 1:signal-handler (1533906750) Received SIGTERM scheduling shutdown...
cc_django_django_1 exited with code 137
postgres_1      | 2018-08-10 13:12:30.517 UTC [1] LOG:  received smart shutdown request
redis_1         | 1:M 10 Aug 13:12:30.517 # User requested shutdown...
redis_1         | 1:M 10 Aug 13:12:30.518 * Saving the final RDB snapshot before exiting.
redis_1         | 1:M 10 Aug 13:12:30.547 * DB saved on disk
redis_1         | 1:M 10 Aug 13:12:30.547 # Redis is now ready to exit, bye bye...
postgres_1      | 2018-08-10 13:12:30.552 UTC [1] LOG:  worker process: logical replication launcher (PID 30) exited with exit code 1
postgres_1      | 2018-08-10 13:12:30.553 UTC [25] LOG:  shutting down
postgres_1      | 2018-08-10 13:12:31.244 UTC [1] LOG:  database system is shut down
cc_django_redis_1 exited with code 0
cc_django_postgres_1 exited with code 0
```

**Comment by browniebroke** [comment]
Just tried today and I can confirm it still happens. Can you elaborate on why is it a problem? For the local container, I don't usually mind much what is the exit code of each container, but maybe I'm missing something...

Anyway, for a solution, I found [this SO answer](https://stackoverflow.com/a/56769138/2261637). I've prefixed the last commands in the shell scripts by `exec` and it seems to work.

**Comment by tlrh314** [comment]
@browniebroke to answer your question why it's important: the current implementation runs the main process (the `command: /start` as defined in the docker-compose files `local.yml`/`production.yml`) in the container as subprocess of pid 1. The problem then is that signals send to the main process running in the Docker container (e.g. `docker-compose -f local.yml stop django`) are not forwarded to the actual running process (which would be `gunicorn` running the Django app). Instead, the Django app runs as a child of `sh -c` with no support for signals. 

This means that the Docker daemon becomes impatient after not having heard back from the main process (which has never received the signal) after the specified timeout (10 seconds by default), and sends a `SIGKILL` rather than `SIGTERM` or `SIGNINT`, or whichever signal you choose to send (manually, e.g. to see how your application handles that). The consequence is that none of the processes have support to receive signals and handle those accordingly.

Indeed, one could not care about exit status of containers that run locally, although the current implementation kills the container after the (default of 10s) Docker timeout. It could be 10s faster to stop/restart local containers when `exec`'ed, and these processes would have proper signal support as intended. More importantly, the production stack suffers from the same issue! Among other issues, this slows down deployment by 10 unnecessary seconds during which the application server just idles to ungraciously kill the process. 

The proposed solution indeed runs the intended main process in the same shell as Docker's main process, i.e. it would receive signals and that would resolve the issue.

I found [this](https://hynek.me/articles/docker-signals/) explanation helpful, although slightly different because here "/start" is not run as entrypoint in shell mode though.
