### ISSUE TITLE
Improve User model methods to get the name

### ISSUE THREAD

**Issue by cachitas** [cookiecutter/cookiecutter-django#3119]
## Description

`User` methods [`get_full_name()`](https://docs.djangoproject.com/en/3.1/ref/contrib/auth/#django.contrib.auth.models.User.get_full_name) and [`get_short_name()`](https://docs.djangoproject.com/en/3.1/ref/contrib/auth/#django.contrib.auth.models.User.get_short_name) should return sensible default values or raise an exception since the fields they rely on are no longer used.

## Rationale

This projects does not make use of `User` fields `first_name` and `last_name`.
Recently, in #2998, these fields were removed from the `User` model altogether.
Calling the methods above do not return meaningful values.

```python
>>> user.get_full_name()
'None None'

>>> user.get_short_name()
None
```

**Comment by bansaljas** [comment]
Hey! I'd like to work on the following issue.
Could you please provide a little bit more information.

I observed in the code that in the User model first and last name fields have been explicitly set to 'None', does this require a change to that?
Thankyou.

**Comment by Andrew-Chen-Wang** [comment]
@cachitas @bansaljas I'm against any changes to those functions since it adds unnecessary code. They really don't make any sense since we use the `name` column/attribute instead of `first_name` and `last_name` for international purposes. `get_full_name` is basically just getting the name attribute. `get_short_name` only makes sense in terms of `first_name`.

**Comment by cachitas** [comment]
> we use the `name` column/attribute instead of `first_name` and `last_name` for international purposes.

I agree that the field `name` is overall better and my intent on opening this issue was not to change that. 

I just wanted to let you know that the methods mentioned above are returning meaningless values and, for consistency, we should adapt them to use the `name` field value somehow.

For instance, we could define them as simple as
```python
def get_full_name(self):
    return self.name
        
def get_short_name(self):
    return self.name.split()[0]
```
Or if you don't want to go into specifics, just `raise NotImplementedError` and let everyone handle it as they see fit. The inconsistency in returning `'None None'` or `None` is what I think could be improved.

Anyway, if in the end you still feel like this adds unnecessary code, feel free to close this :)

**Comment by Andrew-Chen-Wang** [comment]
just a person with some thoughts :) I like the idea of `raise NotImplementedError` to signify to the dev that they really shouldn't be using those methods anymore!

**Comment by browniebroke** [comment]
I agree with @Andrew-Chen-Wang here. If we're talking about adding these methods just for the sake of adding them, then I'm -1 on this. 

If this is causing a lot of issues with some third party django packages that rely on them, we might consider fixing these, but I don't think that's the case (otherwise this issue would get a lot more attention).
