### ISSUE TITLE
Celery ports issues on local docker

### ISSUE THREAD

**Issue by professorhaseeb** [cookiecutter/cookiecutter-django#3240]
when deploying locally on docker. i got this error

`services.celeryworker.ports must be a list`
`services.celerybeat.ports must be a list`

### Fix
removed `ports: []` from `celerybeat` and `celeryworker` in `local.yml`

**Comment by luzfcb** [comment]
@professorhaseeb 
I was unable to reproduce the mentioned error locally. Can you please inform:

- Operational system:
  On Linux, run 
  ```bash
  lsb_release -a 2> /dev/null || cat /etc/redhat-release 2> /dev/null || cat /etc/*-release 2> /dev/null || cat /etc/issue 2> /dev/null`
  ```
  On MacOS, run 
  ```bash
  sw_vers
  ```
- Docker version (run `docker --version`):
- docker-compose version (run `docker-compose --version`):

**Comment by luzfcb** [comment]
@professorhaseeb

**Comment by firstdayofjune** [comment]
After updgrading docker desktop to the latest version on MacOS, I had the same issue, today. With the upgrade, docker compose is also upgraded to the latest beta-version.
Disabling _Docker Compose V2_ in the _Experimental Features_ settings solves the issue for me:

![image](https://user-images.githubusercontent.com/2797104/124151326-b9125980-da92-11eb-8d0e-4ade68f65912.png)

To me, this seems to be a docker issue, rather than a problem with the cookiecutter template. Alas, I could not find any information whether the syntax for overriding ports changed between versions of docker compose.

So I guess it may still be necessary to find out for sure, if the template had to be changed for compatibility with the latest compose version. In the meantime, disabling the docker compose beta version seems to be a legitimate workaround.

I still provide the requested version information for reproducibility:

```
> sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71

> docker --version
Docker version 20.10.7, build f0df350

> docker-compose --version
Docker Compose version 2.0.0-beta.4
```

... after disabling V2:
```
> docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```

**Comment by browniebroke** [comment]
I assume this is solved and can be closed, right?
