### ISSUE TITLE
Django-tailwind NPM_BIN_PATH location node

### ISSUE THREAD

**Issue by adammakowskidev** [cookiecutter/cookiecutter-django#3390]
Hi
Im trying to use django-tailwind
https://github.com/timonweb/django-tailwind
I use Django Cookiecutter with node docker image
I have a problem with the location NPM_BIN_PATH
Does anyone know how to point to the correct location for node docker image?

```

CommandError: 
It looks like node.js and/or npm is not installed or cannot be found.

Visit https://nodejs.org to download and install node.js for your system.

If you have npm installed and still getting this error message, set NPM_BIN_PATH variable in settings.py to match path of NPM executable in your system.

Example:
NPM_BIN_PATH = "/usr/local/bin/npm"

```

**Comment by foarsitter** [comment]
This is the image of your local docker Django container: https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/local/django/Dockerfile
Do you notice the word `node` does not occur at all?  Thats right, the node container is responsible for the processing of css and js and is complete separated from the Django container.  Reference npm in the Django container is thus not posible since it is not installed at all. 

You need to modify the Django Dockerfile and install node by yourself. This guide will help you (option 2 has my preference): https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04 

Last but not least: if you need help github issues is not the best place to get it. Try stackoverflow for issues not related to this project.
