### ISSUE TITLE
pre-commit/action is deprecated

### ISSUE THREAD

**Issue by jpmckinney** [cookiecutter/cookiecutter-django#3395]
Its documentation instead recommends using https://pre-commit.ci/

https://github.com/pre-commit/action

**Comment by Andrew-Chen-Wang** [comment]
This affects generated templates https://github.com/cookiecutter/cookiecutter-django/blob/8cf57ca1872508874c50da0493dc22df6827066c/%7B%7Bcookiecutter.project_slug%7D%7D/.github/workflows/ci.yml#L34-L35

If there are alternative GitHub Actions rather than using pre-commit's CI itself, that'd be great since many people use cookiecutter-django in private repos. Additionally, it's in maintenance mode, so I'm not really panicking. We could perhaps leave a note saying "if your project is open source, please use pre-commit.ci"
