### ISSUE TITLE
django-debug-toolbar 3.2.3 introduced APPS_DIR set to True warning

### ISSUE THREAD

**Issue by mpoli** [cookiecutter/cookiecutter-django#3475]
## What happened?

https://github.com/cookiecutter/cookiecutter-django/pull/3466 bumped django-debug-toolbar to version 3.2.3. This version introducted the following WARNING into Django, which persisted in 3.2.4:

````
django      | System check identified some issues:
django      |
django      | WARNINGS:
django      | ?: (debug_toolbar.W006) At least one DjangoTemplates TEMPLATES configuration needs to have APP_DIRS set to True.
django      |   HINT: Use APP_DIRS=True for at least one django.template.backends.django.DjangoTemplates backend configuration.
````

## What should've happened instead?

No warning should have been shown.

## Additional details

The APPS_DIR situation also surfaces when implementing some packages like django-sitemaps, that  also tells that it is necessary to have at least one APPS_DIR=True somewhere in the templating options ([check the docs](https://docs.djangoproject.com/en/4.0/ref/contrib/sitemaps/#installation)).

cookiecutter-django's current approach seems to accomplish similar results by using template-dir by template-dir approarch instead of the APPS_DIR=True catchall. That might be a good thing, but somehow at least in two instances (one part of cookiecutter-django and one that seems to be part of the Django Project itself) are complaining about this.

So the question is: is there a workaround that warning, and a way to circumvent django-sitemaps instructions and keep the current templating approach? And is there any downside to having it instead of the APPS_DIR=True solution?

* Host system configuration:
    * Version of cookiecutter: Cookiecutter 1.7.3
    * OS name and version: docker
    * Python version: 3.10
    * Docker version: 20.10.10
    * docker-compose version: 1.29.2
    * cookiecutter-django version: **2021.12.15**
    *  django-debug-toolbar: **3.2.4**

**Comment by browniebroke** [comment]
Thanks for the report. That's too bad we didn't see it in tests, I see the warning is there. To avoid this to happen in the future, we should probably include a call to `python manage.py check --fail-level WARNING` as part of our CI.

No idea why we don't have `APPS_DIR=True` in the project...

> somehow at least in two instances (one part of cookiecutter-django and one that seems to be part of the Django Project itself) are complaining about this.

Could you expand on that? Is it that 2 places aren't acceptiong the catchall setting?

**Comment by mpoli** [comment]
When faced with django-sitemaps instructions, I added the APPS_DIR=True in settings/base-py under TEMPLATES = []. Django will quit on a config error.

It is incompatible with the "loaders": [] way that cookiecutter-django does it. They are mutually excludent somehow.

**Comment by browniebroke** [comment]
Ok, so I looked at this more closely. Setting `APP_DIR=True` is equivalent to [adding the `app_directories.Loader`](https://docs.djangoproject.com/en/dev/ref/templates/api/#django.template.loaders.app_directories.Loader):

> django.template.loaders.app_directories.Loader
> ...
> You can enable this loader by setting `APP_DIRS` to `True`

Looks like our settings locally are the same as if we were just setting `APP_DIRS` to `True` since the other one we use is enabled by default.

We don't set `APP_DIRS` to `True` because our prod setup is a bit more optimised. We alter the default config to wrap our loaders with [`cached.Loader`](https://docs.djangoproject.com/en/dev/ref/templates/api/#django.template.loaders.cached.Loader): 

https://github.com/cookiecutter/cookiecutter-django/blob/ce1c76e34e60395b3d012f9037e138651159459e/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/production.py#L129-L137

Now, looking at the documentation again, I see this note:

> This loader is automatically enabled if `OPTIONS['loaders']` isn’t specified and `OPTIONS['debug']` is `False` (the latter option defaults to the value of `DEBUG`).

If I'm reading all this correctly, it looks like our setup can be simplified as follows:

- Add `'APP_DIRS': True`
- Don't specificy the `loaders` option (we use the default values)
- Remove the above lines from `production.py` where we chenge the `loaders` option in `TEMPLATES` 

I'm not touching templates setting very often, hopefully I've read the docs correctly... Am I missing anything?
