### ISSUE TITLE
Python 3.7 support still available?

### ISSUE THREAD

**Issue by datatalking** [cookiecutter/cookiecutter-django#3863]
## What happened?

I have the same question as this but it was never answered. https://github.com/awesto/cookiecutter-django-shop/issues/29
Does Cookiecutter support python 3.7? Where can I find what versions of python it supports?
I'm in the process of migrating a bunch of small scripts up from python 2.7 to python 3.7 and then once its all working we will move it up to 3.9 but I was told by several people that cookiecutter-django isn't compatible with python 3.7. Is that true?

Also how does Django handle multiple versions of python on the backend? The reason I ask is we have about three different versions of python as some of the NLP and language modeling programs are custom written using old pypi files that the highest level of python they support is 3.7. I'm trying to write as much as I can but there are dozens and dozens of scripts that are not supported past 3.7.

**Comment by datatalking** [comment]
So I'm seeing now you support 3.7 and above as 3.6 was removed in (issue #1608)[Removed support for Python 3.6 and PyPy (#1608) @audreyfeldroy]

So it states support for 2.7 was dropped in (#1386) @ssbarnea but prior to that did people have success with 2.7 in a docker which is a new area of need for my team thus the reliance upon cookie cutter, this makes it fantastic to update code and rebuild it.

**Comment by browniebroke** [comment]
Did you mean to open this issue on the https://github.com/cookiecutter/cookiecutter repo? 

This repo generates a project running Python 3.9 and that's it. It might work with Python 3.7, but there is no guarantee it'll work, and we don't have the bandwidth to support more than 1 version of Python. Since it's generating application and not a library, there is in practice little need for it.
