### ISSUE TITLE
Worker node is offline

### ISSUE THREAD

**Issue by morenoh149** [cookiecutter/cookiecutter-django#3912]
## What happened?

after running the app for some time I see the following

```bash
local_celeryworker | [18:16:42] 1898 changes detected                                                                                                                                                                     
local_celeryworker |                                                                                                                                                                                                      
local_celeryworker | worker: Hitting Ctrl+C again will terminate all running tasks!                                                                                                                                       
local_celeryworker |                                                                                                                                                                                                      
local_celeryworker | worker: Warm shutdown (MainProcess)   
```

## What should've happened instead?

celery should work even if files change

## Additional details

* Host system configuration:
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): 2.1.1
    * OS name and version:

```bash
     % sw_vers
ProductName:    macOS
ProductVersion: 11.6
BuildVersion:   20G165
```

    * Python version, run `python3 -V`:
    * Docker version (if using Docker), run `docker --version`:
    * docker-compose version (if using Docker), run `docker-compose --version`:
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and MacOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
  (Please, take care to remove sensitive information)
    ```json
    # Insert here the replay file content
    ```
<summary>
Logs:
<details>
<pre>
$ cookiecutter https://github.com/cookiecutter/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by morenoh149** [comment]
if watchdog kills the docker container, we may have to add a restart policy to the compose file

https://github.com/hkotka/docker-container-watchdog/blob/master/docker-compose.yml#L16

```
services:
    celeryworker:
    <<: *django
      ...
      restart: always
```

**Comment by browniebroke** [comment]
Looks like I completely missed this one, is it still an issue? It seems like the shutdown is caused by a relatively large number of files being changed... 

> if watchdog kills the docker container

I don't think the CLI watching files (`[watchfiles](https://github.com/cookiecutter/cookiecutter-django/blob/0958e8887455fead445c7817dd65f5ed9dcae621/%7B%7Bcookiecutter.project_slug%7D%7D/compose/local/django/celery/worker/start#L7)`) has the power to kill the Docker container. I wonder if it could have somehow the container to exhaust some resources and caused Docker to kill the container/the OS to kill the process?

This seems tricky to reproduce, so unless you can provide more details, we might not be able to do anything here. You might have more luck in [the upstream repo](https://github.com/samuelcolvin/watchfiles).

**Comment by morenoh149** [comment]
I no longer have that project. Hopefully someone else tries using celery.
