### ISSUE TITLE
Replace mailhog with mailpit

### ISSUE THREAD

**Issue by foarsitter** [cookiecutter/cookiecutter-django#3964]
## Description

Since a long time we rely on mailhog in development without much of a hassle. Although mailhog isn't maintained anymore it seems to work fine for Django and this particular project

In another (non Django) project we experience some issues with the [parsing of multipart](https://github.com/mailhog/MailHog/issues/411) headers.

The successor of mailhog, [mailpit](https://github.com/axllent/mailpit/) doesn't have this issue and is actively maintained. 

## Rationale

I would like to propose to replace mailhog with mailpit so even our mail container is actively maintained.

**Comment by browniebroke** [comment]
I didn't know mailhog was no longer maintained, I'm not using much myself... Looking at the repo activity, I think you're right: issues and PR are being opened but receive little attention, no many commits in past years.

I don't have any objections to move to something else, especially since you're bringing a good reason to do so. PR welcome. Should hopefully be an easy one?
