### ISSUE TITLE
Webpack and django.test.client.Client

### ISSUE THREAD

**Issue by foarsitter** [cookiecutter/cookiecutter-django#4126]
Using the django test client in combination with webpack raises an error during tests because the stats file is missing. 

```python
webpack_loader.exceptions.WebpackLoaderBadStatsError: The stats file does not contain valid data. Make sure webpack-bundle-tracker plugin is enabled and try to run webpack again.
```

Seems related to https://github.com/django-webpack/django-webpack-loader/issues/187

**Comment by browniebroke** [comment]
Thanks for the report. That issue seems relevant indeed. When you say "Using the django test client", you mean that the `TestCase.client` (an instance of `django.test.client.Client`), right?

I was wondering why [we're not seeing this problem on our own CI](https://github.com/cookiecutter/cookiecutter-django/actions/runs/4074019255/jobs/7018649412#step:7:458), and I think it's because we don't have any tests using it.

Did you manage to fix it in your project?

**Comment by foarsitter** [comment]
One cannot speak of solving by just adding `webpack-stats.json` to git I guess, but that is what I did. 

Reading the linked issue I see two options to solve the problemen. Adding a line to the pipelines and create the file on the fly.

```shell 
echo '{"status":"done","publicPath": "/static/webpack_bundles/","chunks": {"main": []}}' > webpack-stats.json
```

Or add a file with the same content to `/webpack/webpack-stats-test.json` and add a line to `settings/test.py`

```python
WEBPACK_LOADER["DEFAULT"]["STATS_FILE"] = BASE_DIR / "webpack/webpack-stats-test.json'"
```

An third option is to create a `TestingWebpackLoader` but does not have my preference since its another python file roaming around.

**Comment by browniebroke** [comment]
https://github.com/cookiecutter/cookiecutter-django/pull/4128
