### ISSUE TITLE
Webpack Infinite Reload, Missing Assets

### ISSUE THREAD

**Issue by nitsujri** [cookiecutter/cookiecutter-django#4190]
## What happened?

Webpack dev server adds a hash to css & js output filenames:

```
  // common.config.js
  output: {
    path: path.resolve(__dirname, '../apps/static/bundles/'),
    publicPath: '/static/bundles/',
    filename: 'js/[name]-[fullhash].js',
    chunkFilename: 'js/[name]-[hash].js',
  },
  ...
  plugins: [
    ...,
    new MiniCssExtractPlugin({ filename: 'css/[name].[contenthash].css' }),
  ],
```

webpack-dev-server kicks off a rebuild which of course changes the file hash, then it tells the browser to reload because of `liveReload: true`. So far so good.

Django's webserver doesn't perform a server restart, so it doesn't pick up the hash changes. This causes the browser (via webpack's js client) to constantly reload in attempts to pick up the filename change.

It's the same reason why we don't use content hashes with `DEBUG=true` with whitenoise?

## What should've happened instead?

The configs in dev, prod should be updated to use content hashes when appropriate.

```
  // dev.config.js
  output: {
    path: path.resolve(__dirname, '../apps/static/bundles/'),
    publicPath: '/static/bundles/',
    filename: 'js/[name].js',
    chunkFilename: 'js/[name].js',
  },
  plugins: [
    new MiniCssExtractPlugin({ filename: 'css/[name].css' }),
  ],

  // prod.config.js
  plugins: [
    new MiniCssExtractPlugin({ filename: 'css/[name].[contenthash].css' }),
  ],

```

**Comment by browniebroke** [comment]
Looks like you found a solution... Do you think you could submit a pull request with the fix?

**Comment by browniebroke** [comment]
I tried to reproduce the problem today and I can't, it works perfectly fine on my end. Here is what I'm doing:

1. Generated a vanilla project with Webpack and Docker, started all services
2. Went to http://localhost:3000/ saw the basic site rendred
3. Changed some CSS properties in `project.sass`, e.g. `body {background-color: $green;}`
4. On save, it triggered a rebuild, and after a coupld of seconds, I saw the changes in my browser. Didn't see any infinite reloading behaviour. I also tried to navigate to other pages, no problems here either.

Either I'm missing something or the problem is now gone. Are you able able to provide more details please?

**Comment by nitsujri** [comment]
@browniebroke thanks for the follow up. I also tried to reproduce this w/ a fresh app and I can't which clearly means there's something going on with my own project. Apologies I should have done this from the start.

I'm closing this for now and will reopen it if I find something beyond my app. Thanks!

**Comment by nitsujri** [comment]
@browniebroke this caused me to dive into WebpackLoader to find out what's causing the failed refresh/update. I quickly traced it to `[if self.config['CACHE']](https://github.com/django-webpack/django-webpack-loader/blob/master/webpack_loader/loader.py#L35)`.

I'm embarrassed to admit how basic this is and apologies for consuming your time.

**Comment by browniebroke** [comment]
> I'm embarrassed to admit how basic this is and apologies for consuming your time.

No worries!
