### ISSUE TITLE
Adding ruff linter

### ISSUE THREAD

**Issue by epou** [cookiecutter/cookiecutter-django#4383]
## Description

Is there any plan to add ruff (https://github.com/astral-sh/ruff) as a linter in the project? 

It has been proven to be 10-100x faster than other linters and looks like an easy integration into the project (compatible with python 3.11, `pyproject.toml` support, pre-commit, ...)

Here's a benchmark I came across: https://pythonspeed.com/articles/pylint-flake8-ruff/

**Comment by luzfcb** [comment]
Extra considerations:

Ruff is a very new project, and [its first prototype was published on 2022-08-09](https://github.com/astral-sh/ruff/tree/0d8e4bd6e9580a2484fa68c45cb3569e0815ac3f), that is, not even 1 year ago, but its development has been very fast since then.

Assuming that Ruff uses semantic versioning and their respective meanings, there is not yet any version marked as stable of Ruff, because he has not yet reached version v1.0.0, it is currently at v0.0.272 so [it's expected to have a lot of unhandled cases](https://github.com/astral-sh/ruff/issues) and a lot of broken compatibility that flake8 and other libraries have fixed many years ago.

I'd like to add Ruff at some point, I'm just not sure from a cookiecutter-django maintainability standpoint if the time is now.

**Comment by epou** [comment]
Linking the ruff roadmap, so we can stay informed of the situation. The stable version looks to be close: https://github.com/astral-sh/ruff/issues/1992

**Comment by mpsantos** [comment]
Any news on this? 
I know ruff is not stable yet, but is being used in a great number of projects and the benefits are huge.

**Comment by Andrew-Chen-Wang** [comment]
I believe now is a good time to switch to ruff at v0.1.x. Microsoft (+ I also saw ruff's README includes a bunch of companies/packages) uses ruff as a replacement for several tools: pyupgrade, flake8, isort, and black.

**Comment by foarsitter** [comment]
We need to discuss which rules we want to apply. Here is the config I applied to a new project. It requires some fixes but no major ones. 
```toml
select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    "N",
    "UP",
    #    "D", # self documenting code
    "YTT",
    #    "ANN", # we should support this in the future but 100+ errors atm
    "ASYNC",
    "S",
    "BLE",
    "FBT",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "T10",
    "DJ",
    "EM",
    "EXE",
    "FA",
    'ISC',
    "ICN",
    "G",
    'INP',
    'PIE',
    "T20",
    'PYI',
    'PT',
    "Q",
    "RSE",
    "RET",
    "SLF",
    "SLOT",
    "SIM",
    "TID",
    "TCH",
    "INT",
    #    "ARG", # Unused function argument: 11 errors
    "PTH",
    #    "TD", # show to do's
    #    "FIX", # apply this rule in the future
    "ERA",
    "PGH",
    "PL",
    "TRY",
    "FLY",
    "PERF",
    "RUF",
]

ignore = [
    "S101", # 	Use of assert detected https://docs.astral.sh/ruff/rules/assert/
    "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
    "SIM102", # sometimes it's better to nest
]
```

**Comment by foarsitter** [comment]
Added ruff in #4834, care to review?
