### ISSUE TITLE
Update or remove install_os_dependencies.sh?

### ISSUE THREAD

**Issue by pydanny** [cookiecutter/cookiecutter-django#599]
I saw people experiencing problems with this utility at PyCon.  There is also http://stackoverflow.com/questions/37467088/cant-run-migrations-when-setting-up-a-project-with-cookiecutter-django

The problem is maintaining global scripts like this is hard, I don't ever use them personally because they are so fragile. I don't teach people to use them for this same reason, in fact, I suggest they stay away from them.

Finally, it's possibly outside the scope of this project. A tutorial for setup is one thing, an official script is another.

Mitigations:
1. Have someone volunteer to actively maintain this particular script, and to resolve questions asked by users of the script. The problem is the nigh complete lack of incentive to do so.
2. Remove these utility scripts from the project, possibly linking to another optional project that includes them.
3. Remove them altogether and stay with tutorials.

Thoughts?

**Comment by valerymelou** [comment]
I think they should be removed.
I'have experienced many package not found errors when trying to install OS dependencies with them. And back that time I was running an up to date Debian Testing system. I tried it again recently with Ubuntu 16.04 (up to date) and it didn't work either.

**Comment by ddiazpinto** [comment]
I think it would be necessary to improve the entire mechanism (not removing it, because it's quite useful), including all the different names and versions of each package for each distribution (including debian, that actually doesn't works). That would resolve all this issues.

**Comment by audreyr** [comment]
If anyone can help us out by submitting a pull request to do the following, we'll consider keeping it:

* Update `install_os_dependencies.sh`
* Document how to use `install_os_dependencies.sh` in a new document in `docs/`

**Comment by luzfcb** [comment]
as a historical reference:

I created this `install_os_dependencies.sh` script and `requirements.apt` file as part of the resolution of the issue https://github.com/pydanny/cookiecutter-django/issues/34 .

I needed to document the non-python dependencies, and rid our users (I'm included in this group) to have the tedious work to check which python dependencies have non-python compilation dependencies (like c/c++ libraries).

In `requirements.apt`, I also needed to document what Y libraries non-python is required by X python library. so I also needed comments in `requirements.apt` file .

however, I needed a simpler way to get all the package names on one line, to be easy to pass them as parameter to `apt-get install`. copy and paste was not being very productive due to comments.

`install_os_dependencies.sh` was created to solve this. parse `requirements.apt` file, get all package names and them pass as parameter to `apt-get install`

it only works with Ubuntu 14.04 and recently also with Ubuntu 16.04, but this is not a problem, since, undocumented restriction of this project only officially support Ubuntu (Ok, the generated project works perfectly on other operational systems without or almost without modification)

this was one of the reasons I have been against the https://github.com/pydanny/cookiecutter-django/pull/250 and https://github.com/pydanny/cookiecutter-django/pull/438

said that, 
This https://github.com/pydanny/cookiecutter-django/pull/605 solves a problem that was introduced in https://github.com/pydanny/cookiecutter-django/commit/2f6315d606043a768356ad1c9f5a907b42576dba and solve #569

**Comment by audreyr** [comment]
I see, thanks for the explanation @luzfcb. I think there was some confusion here on our part, sorry about that. 

I like #605. I will try to get to reviewing it asap.

**Comment by browniebroke** [comment]
I'm closing this old issue. We've keeping this script up to date and, as far as know, there has been little to no complains with it.
